#!/usr/bin/env python3
"""Assemble rooms/world.txt from the authored row files plus r22, filling any room
that has not been authored yet with a bare template so the build always runs."""
import re, glob, sys, os
have = {}
for f in sorted(glob.glob('rooms/row*.txt')) + sorted(glob.glob('rooms/r[0-9][0-9].txt')):
    if not os.path.exists(f): continue
    for blk in re.split(r'\n(?=ROOM )', open(f).read().strip()):
        lines = blk.split('\n')
        have[lines[0].split()[1]] = (lines[0], [l for l in lines[1:] if l.strip()])
tm = {}
for f in glob.glob('rooms/tmpl/*.txt'):
    k = f.split('/')[-1][:-4].replace('_', ',')
    tm[k] = [l.rstrip('\n') for l in open(f) if l.strip()]
out = ["; GENERATED by tools/assemble.py from rooms/row*.txt + rooms/r22.txt"]
pending = []
for y in range(5):
    for x in range(5):
        k = f"{x},{y}"
        if k in have:
            hdr, g = have[k]
        else:
            pending.append(k)
            g = [list(r) for r in tm[k]]
            for c in range(1, 39): g[19][c] = '#'; g[20][c] = '#'
            g = ["".join(r) for r in g]
            hdr = f"ROOM {k} teaches=PENDING"
        out.append(hdr); out += g; out.append("")
open('rooms/world.txt', 'w').write("\n".join(out) + "\n")
print(f"assembled {len(have)} authored" + (f", {len(pending)} pending: {pending}" if pending else ", all 25 authored"))
