"""Package generated art as embedded JPEG data; no runtime file reads.

Only format conversion occurs here. Governing reference PNGs remain untouched.
Run with the bundled/standard Python and Pillow after the two matte references exist.
"""
from pathlib import Path
from io import BytesIO
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    ("vault_matte", "public/art/references/vault-mouth/02-vault-city-distant-matte.png"),
    ("drowned_matte", "public/art/references/drowned-quarter/02-drowned-city-distant-matte.png"),
]
target = ROOT / "src/generated/environment_mattes.h"
target.parent.mkdir(parents=True, exist_ok=True)
parts = ["// Generated by tools/embed-mattes.py. Original art and prompts in public/art/references.\n"]
for name, relative in SOURCES:
    source = ROOT / relative
    if not source.exists():
        if name == "vault_matte":
            raise FileNotFoundError(source)
        parts.append(f"#define {name.upper()}_AVAILABLE 0\n")
        continue
    buffer = BytesIO()
    with Image.open(source) as image:
        image.convert("RGB").save(buffer, format="JPEG", quality=90, optimize=True)
    data = buffer.getvalue()
    parts.append(f"#define {name.upper()}_AVAILABLE 1\nstatic const unsigned char {name}[] = {{\n")
    parts.extend(",".join(f"0x{v:02x}" for v in data[i:i+24])+",\n" for i in range(0,len(data),24))
    parts.append("};\n")
    print(f"{name}: {len(data):,} embedded bytes from {relative}")
target.write_text("".join(parts), encoding="utf-8")
