#!/usr/bin/env python3
"""Compile rooms/world.txt into src/rooms_gen.h.

Assets are embedded in the binary, never streamed from disk (anti-pattern), so the
authored text becomes a static C array at build time. Also validates the world:
legal tiles, exactly one start, matching openings on every shared edge, and sealed
world boundaries.
"""
import sys, re, os

W, H = 5, 5
RW, RH = 40, 22

TILES = {
    '.': 'T_EMPTY',  '#': 'T_ROCK',   'X': 'T_DARK',   '-': 'T_LEDGE',
    'T': 'T_TIMBER', '~': 'T_BRINE',  '=': 'T_CRUST',  'R': 'T_RIM',
    ',': 'T_GRASS',  'B': 'T_BELL',
}
SOLIDISH = set('#XRB')          # blocks a body outright
OPEN     = set('.-T~=,')       # a body can occupy or pass

def die(msg):
    print("ERROR: " + msg, file=sys.stderr)
    sys.exit(1)

def parse(path):
    rooms, meta = {}, {}
    cur, lines = None, []
    for ln, raw in enumerate(open(path, encoding='utf-8'), 1):
        line = raw.rstrip('\n')
        if line.startswith(';') or (not line.strip() and cur is None):
            continue
        m = re.match(r'^ROOM\s+(\d),(\d)\s*(.*)$', line)
        if m:
            if cur is not None:
                rooms[cur] = lines
            cur = (int(m.group(1)), int(m.group(2)))
            if cur in rooms: die(f"line {ln}: room {cur} declared twice")
            meta[cur] = m.group(3).strip()
            lines = []
            continue
        if cur is None: die(f"line {ln}: content before any ROOM header")
        if not line.strip(): continue
        lines.append(line)
    if cur is not None: rooms[cur] = lines
    return rooms, meta

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'rooms/world.txt'
    out = sys.argv[2] if len(sys.argv) > 2 else 'src/rooms_gen.h'
    rooms, meta = parse(src)

    missing = [(x, y) for y in range(H) for x in range(W) if (x, y) not in rooms]
    if missing: die(f"missing rooms: {missing}")

    starts = []
    for (x, y), lines in sorted(rooms.items()):
        if len(lines) != RH: die(f"room {x},{y}: {len(lines)} rows, need {RH}")
        for r, row in enumerate(lines):
            if len(row) != RW: die(f"room {x},{y} row {r}: {len(row)} cols, need {RW}")
            for c, ch in enumerate(row):
                if ch == 'P': starts.append((x, y, c, r)); continue
                if ch not in TILES: die(f"room {x},{y} row {r} col {c}: illegal tile {ch!r}")
    if len(starts) != 1: die(f"need exactly one P start, found {len(starts)}")

    def at(x, y, c, r):
        ch = rooms[(x, y)][r][c]
        return '.' if ch == 'P' else ch

    # Shared edges must agree: an opening on one side needs an opening opposite it,
    # or the player walks into a wall that was drawn as a door.
    problems = []
    for y in range(H):
        for x in range(W):
            if x + 1 < W:
                for r in range(RH):
                    a, b = at(x, y, RW - 1, r), at(x + 1, y, 0, r)
                    if (a in OPEN) != (b in OPEN):
                        problems.append(f"({x},{y})|({x+1},{y}) row {r}: {a!r} vs {b!r}")
            if y + 1 < H:
                for c in range(RW):
                    a, b = at(x, y, c, RH - 1), at(x, y + 1, c, 0)
                    if (a in OPEN) != (b in OPEN):
                        problems.append(f"({x},{y})/({x},{y+1}) col {c}: {a!r} vs {b!r}")
    # world boundary must be sealed
    for y in range(H):
        for r in range(RH):
            if at(0, y, 0, r) in OPEN: problems.append(f"({0},{y}) row {r}: world edge open on the left")
            if at(W - 1, y, RW - 1, r) in OPEN: problems.append(f"({W-1},{y}) row {r}: world edge open on the right")
    for x in range(W):
        for c in range(RW):
            if at(x, 0, c, 0) in OPEN: problems.append(f"({x},0) col {c}: world edge open on top")
            if at(x, H - 1, c, RH - 1) in OPEN: problems.append(f"({x},{H-1}) col {c}: world edge open on the bottom")

    if problems:
        for p in problems[:40]: print("EDGE: " + p, file=sys.stderr)
        if len(problems) > 40: print(f"... and {len(problems)-40} more", file=sys.stderr)
        die(f"{len(problems)} edge mismatches")

    sx, sy, sc, sr = starts[0]
    with open(out, 'w') as f:
        f.write("// GENERATED by tools/genrooms.py from rooms/world.txt. Do not edit.\n")
        f.write("#ifndef ROOMS_GEN_H\n#define ROOMS_GEN_H\n\n")
        f.write(f"#define START_ROOM_X {sx}\n#define START_ROOM_Y {sy}\n")
        f.write(f"#define START_TILE_X {sc}\n#define START_TILE_Y {sr}\n\n")
        f.write("static const u8 roomData[ROOM_COUNT][RH][RW] = {\n")
        for y in range(H):
            for x in range(W):
                f.write(f"  /* ({x},{y}) */ {{\n")
                for r in range(RH):
                    row = ",".join(TILES[at(x, y, c, r)] for c in range(RW))
                    f.write("    {" + row + "},\n")
                f.write("  },\n")
        f.write("};\n\n#endif\n")

    print(f"OK  25 rooms  start=({sx},{sy}) tile ({sc},{sr})  -> {out}")
    for (x, y) in sorted(rooms, key=lambda k: (k[1], k[0])):
        if meta[(x, y)]:
            print(f"    ({x},{y})  {meta[(x,y)]}")

main()
